### ISSUE TITLE
appTsConfig.compilerOptions[option] = value; Error

### ISSUE THREAD

**Issue by justinpezzack** [phantom-labs/sandbox#11]
justinpezzack@DESKTOP-GILEO49:~/sandbox$ npm start

> react-typescript@1.0.0 start /home/justinpezzack/sandbox
> react-scripts start

/home/justinpezzack/sandbox/node_modules/react-scripts/scripts/utils/verifyTypeScriptSetup.js:239
      appTsConfig.compilerOptions[option] = value;
                                          ^

TypeError: Cannot assign to read only property 'jsx' of object '#<Object>'
    at verifyTypeScriptSetup (/home/justinpezzack/sandbox/node_modules/react-scripts/scripts/utils/verifyTypeScriptSetup.js:239:43)
    at Object.<anonymous> (/home/justinpezzack/sandbox/node_modules/react-scripts/scripts/start.js:31:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47

When trying to build sandbox locally.

**Comment by fragosti** [comment]
This is fixed now.
